### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by ice1000** [aya-prover/intellij-aya#32]
```
java.lang.AssertionError
	at org.aya.intellij.psi.AyaPsiFile.containingFileModule(AyaPsiFile.java:36)
	at org.aya.intellij.psi.AyaPsiElement.presentableName(AyaPsiElement.java:42)
	at org.aya.intellij.psi.AyaPsiElement.ayaPresentation(AyaPsiElement.java:36)
	at org.aya.intellij.ui.structure.AyaNavBar.getIcon(AyaNavBar.java:22)
	at com.intellij.platform.navbar.backend.compatibility.DefaultNavBarItem$presentation$icon$1.invoke(DefaultNavBarItem.kt:52)
	at com.intellij.platform.navbar.backend.compatibility.DefaultNavBarItem$presentation$icon$1.invoke(DefaultNavBarItem.kt:52)
	at com.intellij.platform.navbar.backend.compatibility.DefaultNavBarItemProviderKt.fromOldExtensions(DefaultNavBarItemProvider.kt:141)
	at com.intellij.platform.navbar.backend.compatibility.DefaultNavBarItem.presentation(DefaultNavBarItem.kt:52)
	at com.intellij.platform.navbar.backend.compatibility.IdeNavBarVmItem.<init>(IdeNavBarVmItem.kt:24)
	at com.intellij.platform.navbar.backend.compatibility.IdeNavBarVmItemKt.toVmItems(IdeNavBarVmItem.kt:74)
	at com.intellij.platform.navbar.monolith.compatibility.MonolithNavbarServiceDelegate$contextModel$2.invoke(MonolithNavBarServiceDelegate.kt:44)
	at com.intellij.platform.navbar.monolith.compatibility.MonolithNavbarServiceDelegate$contextModel$2.invoke(MonolithNavBarServiceDelegate.kt:39)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1$lambda$0(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1(cancellableReadAction.kt:29)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:27)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:77)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)

```

**Comment by ice1000** [comment]
Fixed
